metaDescription: I'm Jared Sorge and this is my website. I'm a Christian, husband, dad, developer, and batman aficianado.
title: jsorge.net
description: Christian, husband, dad, developer, batman afficianado.
url: https://jsorge.net
batchSize: 20
